force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <description>This object is hold all requiter detail</description>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Mangeres</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <inlineHelpText>Please provide the phone number</inlineHelpText>
    <label>Contact Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <inlineHelpText>Provide the valid email id</inlineHelpText>
    <label>Email Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Patna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object is used to hold the all the open  position in the organization.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <referenceTo>Hiring_Manager__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/HR_email_ID__c.field-meta.xml
<CustomField>
    <fullName>HR_email_ID__c</fullName>
    <label>HR email ID</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Maximum_Pay__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Pay__c</fullName>
    <label>Maximum Pay</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Minimum_Pay__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Pay__c</fullName>
    <label>Minimum Pay</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Number_of_Position__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Position__c</fullName>
    <label>Number of Position</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Open_Date__c.field-meta.xml
<CustomField>
    <fullName>Open_Date__c</fullName>
    <label>Open Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Passport_Required__c.field-meta.xml
<CustomField>
    <fullName>Passport_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passport Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Description__c.field-meta.xml
<CustomField>
    <fullName>Position_Description__c</fullName>
    <label>Position Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Status__c.field-meta.xml
<CustomField>
    <fullName>Position_Status__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
                <default>true</default>
                <label>New Position</label>
            </value>
            <value>
                <fullName>Open Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Recruited</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Skills_Required__c.field-meta.xml
<CustomField>
    <fullName>Skills_Required__c</fullName>
    <label>Skills Required</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/CommonUtility.cls
public class CommonUtility
{
	// User to insert a Hiring Manager Record
	public void InsertHiringManagerRecord()
    {
        // Creating the object for the Hiring_manager__c class...
       Hiring_manager__c hr = new Hiring_manager__c();
        // Assign the vlaue...
        
        hr.Name = 'Mukul Kumar';
        hr.Location__c = 'Bangalore';
        hr.Email_Id__c = 'sridhar@gmail.com';
        hr.Contact_Number__c = '99998899';
        
        // inser the record..
        insert hr;
        if(hr.Id != null)
        {
            system.debug('Hiring Manager record has been created successfully and record ID is....'+ hr.Id);
        }
	}
     
    // Used to create a position Record..
    public void CreateNewPosition()
    {
        // Create the object for the Position__c class
        
        Position__c pos = new Position__c();
        
        // Assgin the value..
        pos.Name = 'Oracle Developer';
        pos.Number_of_Position__c = 4;
        pos.Location__c = 'Bangalore';
        pos.Position_Status__c = 'New Position';
        
        pos.Open_Date__c = system.today();
        pos.Close_Date__c = system.today().AddDays(20);
        
        pos.Minimum_Pay__c = 900000;
        pos.Maximum_Pay__c = 1300000;
        
        pos.Travel_Required__c = true;
        pos.Passport_Required__c = true;
        
        pos.HR_email_ID__c = 'sweta@gmail.com';
        
        pos.Position_Description__c = 'Required 3+ years experience in c++ Application Developere';
        pos.Skills_Required__c = 'Required 3+ years experience in c++ Application Developere';
        
        pos.RecordTypeId = Schema.SObjectType.Position__c.GetRecordTypeInfosByName().Get('IT Position Record Type').GetRecordTypeId();
        
        // Insert the Position record
        
        insert pos;
        
        if(pos.Id != null)
        {
            System.debug('Position record inserted successfully with record ID is.... '+ pos.Id);
         }
        
        
    }
}