force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <description>This object is hold all requiter detail</description>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Mangeres</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <inlineHelpText>Provide the valid email id</inlineHelpText>
    <label>Email Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Patna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CommonHelper.cls
public class CommonHelper 
{
    // to fetch all lead records...
    public static void GetLeadRecord()
    {
        list<lead> lstlead = [select id, firstname, lastname, email, company,status from lead];
        
        system.debug('Result set collection size is.. '+ lstlead.size());
        if(!lstlead.isEmpty())
        {
            for(lead ld :lstlead)
            {
                system.debug('lead id is --- '+ ld.id);
                system.debug('lead id is --- '+ ld.firstname+ ' '+ ld.LastName);
                system.debug('lead email id is --- '+ ld.email);
                system.debug('lead company is --- '+ ld.company);
                system.debug('lead status is --- '+ ld.status);
                
                System.debug('======================================');
            }
        }
    }
    
	public void GetAllHiringManager()
    {
        list<Hiring_Manager__c> lstManager = [select id, name, location__c, email_id__c from Hiring_Manager__c];
        
        system.debug('Hiring Manager collection size is...' + lstManager.size());
        
        if(! lstManager.isEmpty())
        {
            for(Hiring_Manager__c hr : lstManager)
            {
                System.debug('Hiring manager record is.... '+ hr);
			}
        }
    }
}