force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <description>This object is hold all requiter detail</description>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Mangeres</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <inlineHelpText>Please provide the phone number</inlineHelpText>
    <label>Contact Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <inlineHelpText>Provide the valid email id</inlineHelpText>
    <label>Email Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Patna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object is used to hold the all the open  position in the organization.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <referenceTo>Hiring_Manager__c</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Maximum_Pay__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Pay__c</fullName>
    <label>Maximum Pay</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Status__c.field-meta.xml
<CustomField>
    <fullName>Position_Status__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
                <default>true</default>
                <label>New Position</label>
            </value>
            <value>
                <fullName>Open Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Recruited</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ChildParentRelationshipSobj.cls
public class ChildParentRelationshipSobj
{
    public static void GetPositionNdHiringManagerByStatus(string positionstatus)
    {
        list<position__c> lstpos = [select id, name, location__c, position_status__c, close_date__c, maximum_pay__c,
                                   Hiring_Manager__r.name, Hiring_Manager__r.location__c, Hiring_Manager__r.email_id__c, Hiring_Manager__r.contact_number__c
                                   from position__c
                                   	where position_status__c =: positionstatus];
        system.debug('collection size is... '+ lstpos.size());
        if(!lstpos.isEmpty())
        {
            for(position__c pos : lstpos)
            {
                system.debug('position name is... '+ pos.name);
                system.debug('psoition location is ... '+ pos.location__c);
                system.debug('Status is... '+ pos.position_status__c);
                system.debug('close date is... '+ pos.close_date__c);
                //Parent details...
                system.debug('Hiring Manager name--- '+ pos.Hiring_Manager__r.name);
                system.debug('Hiring Manager Location is.... '+ pos.Hiring_Manager__r.location__c);
                system.debug('Hiring Manager email id is.... '+ pos.Hiring_Manager__r.email_id__c);
                
                
            }
        }
    }
    
    public static void GetcontactAndAssociatedParentDetails(String contactlastname)
    {
        string contquery ='select id, firstname, lastname, email, phone, fax, account.name, account.rating, account.industry, account.type, account.active__c, account.owner.firstname, account.owner.lastname, account.owner.email from contact where lastname =: contactlastname and accountid != null';
       
        
       list<contact> lstcon = Database.query(contquery);
        
        system.debug('Contact collection size is... '+ lstcon.size());
        
        if(!lstcon.isEmpty())
        {
            for(contact co : lstcon)
            {
                System.debug('Contact name is.... '+ co.FirstName +' '+ co.LastName);
                system.debug('conatct email is.. '+ co.Email);
                system.debug('contact phone is... '+ co.Phone);
                
                //Parent record detail
                system.debug('Parent account name is... '+ co.account.name);
                
                system.debug('Parent account rating is... '+ co.account.rating);
                
                system.debug('Parent account active status is... '+ co.account.active__c);
                
                //Grand parent record detail
                system.debug('Account owner name is.. '+ co.account.owner.firstname + ' '+ co.account.owner.lastname);
                
                system.debug('Account owner name is.. '+ co.account.owner.email);
                
            }
        }
    }

}