force-app/main/default/objects/Hiring_Manager__c/Hiring_Manager__c.object-meta.xml
<CustomObject>
    <description>This object is hold all requiter detail</description>
    <label>Hiring Manager</label>
    <nameField>
        <label>Hiring Manager Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hiring Mangeres</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Hiring_Manager__c/fields/Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Contact_Number__c</fullName>
    <inlineHelpText>Please provide the phone number</inlineHelpText>
    <label>Contact Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <inlineHelpText>Provide the valid email id</inlineHelpText>
    <label>Email Id</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Hiring_Manager__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Patna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DMLOperationss.cls
public class DMLOperationss 
{
   
    // insert Hiring manager records
    public static void CreateBulkHiringManagerRecord(integer recordsTOinsert)
    {
     for(integer counter = 1; counter <= recordsTOinsert; counter++)
     {
         Hiring_Manager__c hr = new Hiring_Manager__c();
         
         hr.Name ='New Recrutier - '+ counter;
         hr.Location__c = 'Chennai';
         hr.Contact_Number__c = '9988775568';
         hr.Email_Id__c = 'newrecruiter'+counter+'@gmail.com';
         
         insert hr;
         if(hr.Id != null)
         {
             system.debug('Record inserted successfully. Record id is... '+ hr.Id);
         }
         
     }
    }
    
        
    public static void InsertNewContact()
    {
        // creating the object for contact class
        Contact con = new Contact();
        
       // Assigning the values for fields...
       con.firstName ='Java';
        con.LastName = 'Programming';
        con.Title = 'Manager';
        con.Birthdate = Date.newInstance(1985, 10, 23);
        con.Phone = '8979879887';
        con.Email = 'javadev@gmail.com';
        con.Pan_Number__c= 'AAOjhPJ87H';
        con.Department = 'Developer';
        
        // insert the record into the object...
        insert con;
        if(con.Id != null)
        {
            system.debug('Contact record inserted sccessfully. contact ID is... '+ con.Id );
        }
    }

}