force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object is used to hold the all the open  position in the organization.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Maximum_Pay__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Pay__c</fullName>
    <label>Maximum Pay</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Status__c.field-meta.xml
<CustomField>
    <fullName>Position_Status__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
                <default>true</default>
                <label>New Position</label>
            </value>
            <value>
                <fullName>Open Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Recruited</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentRecrod.cls
/*
Write an apex program to fetch all candidate record and fetch all candidate records and store it into "Map" collection.

*/

public class StudentRecrod 
{
	public static void GetPostionRecrod()
    {
        Map<id, position__c> mapPos = new Map<id, position__c>([select id, name, location__c, position_status__c,
                                     maximum_pay__c,close_date__c from Position__c]);
        
        if(!mapPos.isEmpty())
        {
            for(Position__c pos : mapPos.values())
            {
                System.debug('Position record id is ---- '+ pos.Id);
                system.debug('Position name is ---- '+ pos.Name);
                system.debug('Position locationo is ...... '+ pos.Location__c);
                system.debug('Position status is ----- '+ pos.Position_Status__c);
                System.debug('Position maximum pay is ..... '+ pos.Maximum_Pay__c);
                system.debug('Position close date is ..... '+ pos.Close_Date__c);
                System.debug('-----------------------------------------------------');
                
			}
		}
       /* Map<id,Position__c> mapPos = new Map<id, Position__c>();
        list<Position__c> lstPos = [select id, name, location__c, position_status__c,
                                     maximum_pay__c,close_date__c from Position__c];
        // copy the record to map....
        if(! lstPos.isEmpty())
        {
            for(Position__c pos: lstPos )
            {
                mapPos.put(pos.id,pos);
			}
        }
	*/
        
        
	}
}