force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object is used to hold the all the open  position in the organization.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/HavinggClass.cls
public class HavinggClass 
{
    public static void GetDuplicateAccByname()
    {
        AggregateResult[] aggresult = [select name, count(id) recordscount from account
                                      group by Name
                                      Having count(id) > 1];
        system.debug('Duplicate account collection size is.. '+ aggresult.size());
        
        if(!aggresult.isEmpty())
        {
            for(AggregateResult res : aggresult)
            {
                system.debug('Account name: '+ res.get('Name') +'----Records count is.. '+ res.get('recordscount'));
            }
		}
    }
    
	public static void GetLocNdPos()
    {
        AggregateResult[] aggResults = [select location__c, count(id) positionscount from Position__c
        									group by Location__c
        									Having count(id) >= 2];
    
    System.debug('Collection count is ...... '+ aggResults.size());
        if(! aggResults.isEmpty())
        {
            for(AggregateResult res : aggResults)
            {
                system.debug('Location name: '+ res.get('Location__c') + '-----Position count: '+ res.get('positionscount'));
            }
        }
    }

}