force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <description>This object is used to hold the all the open  position in the organization.</description>
    <label>Position</label>
    <nameField>
        <label>Position Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Close_Date__c</fullName>
    <label>Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Hyderabad</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Maximum_Pay__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Pay__c</fullName>
    <label>Maximum Pay</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Minimum_Pay__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Pay__c</fullName>
    <label>Minimum Pay</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Position_Status__c.field-meta.xml
<CustomField>
    <fullName>Position_Status__c</fullName>
    <label>Position Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New Position</fullName>
                <default>true</default>
                <label>New Position</label>
            </value>
            <value>
                <fullName>Open Approved</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Recruited</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DynamicSoql.cls
public class DynamicSoql 
{
    
    public static void GetPositionStatus(String posStatus)
    {
        if(posStatus != null && posStatus !='')
        {
            string positionQuery ='Select id, name, location__c, position_status__c, minimum_pay__c, close_date__c, maximum_pay__c from position__c where position_status__c =:PosStatus';
            
            List<Position__c> lstpos = DataBase.query(positionquery);
            system.debug('Collection size is .... '+ lstpos.size());
            
            if(! lstpos.isEmpty())
            {
                for(Position__c pos : lstpos)
                {
                    system.debug('Position record is.....'+ pos);
				}
			}
            
            
		}
	}
    
    /*
	public static void GetContactsBySearchText(String searchText)
    {
        if(searchText != null && searchText != '')
        {
            string contactsQuery = 'select id, firstname, lastname,email, title, phone, fax, birthdate from contact';
       if(Pattern.matches('^[a-zA-Z0-9._|\\\\%#~`=?&/$^*!}{+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$', searchText))
       {
        System.debug('User input is in email format'); 
           contactsQuery += 'Where email =: searchText';
       }
            else
            {
                system.debug('User input is in string format ');
                searchText += '%';
            contactsQuery += 'Where lastname like: searchText';
            }
            system.debug(' Qery is ...'+ contactsQuery);
            
            // Execute the query
            list<contact> lstcont = Database.query(contactsQuery);
            system.debug('Search result count is ....: '+ lstcont.size());
            if(! lstcont.isEmpty())
            {
                for(Contact con : lstcont)
                {
                    System.debug('Contact record is..'+ con);
                }
            }
                        
        }
    }
	*/
     public static void GetContactsBySearchText(string searchText)
    {
        if(searchText != null && searchText != '')
        {
            string contactsQuery = 'select id, firstname, lastname, email, title, phone, fax, birthdate from contact ';
            if(pattern.matches('^[a-zA-Z0-9._|\\\\%#~`=?&/$^*!}{+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$', searchText))
            {
                system.debug('User input is in email format');
                contactsQuery += 'where email =:  searchText';
                
                
            }
            else
            {
                system.debug('User input is a string');
                searchText += '%';
				contactsQuery += 'where lastname Like :  searchText';

            }
           
            // Execute the query
            List<Contact> lstContacts = Database.query(contactsQuery);
            system.debug('Search results count is:' + lstContacts.size());
            if(! lstContacts.isEmpty())
            {
                for(contact con : lstContacts)
                {
                    system.debug('Contact record is: '+ con);
                }
            }
            
        }
        
    }
	
}