force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <label>Candidate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Candidate_ID_c__c.field-meta.xml
<CustomField>
    <fullName>Candidate_ID_c__c</fullName>
    <displayFormat>CID-{000000}</displayFormat>
    <label>Candidate ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Candidature_Status__c.field-meta.xml
<CustomField>
    <fullName>Candidature_Status__c</fullName>
    <label>Candidature Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Sent for Screening</fullName>
            </value>
            <value>
                <fullName>Shortlisted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Get the availability</fullName>
            </value>
            <value>
                <fullName>Schedule the Interview</fullName>
            </value>
            <value>
                <fullName>HR Round</fullName>
            </value>
            <value>
                <fullName>Release the offer</fullName>
            </value>
            <value>
                <fullName>Recruited</fullName>
            </value>
            <value>
                <fullName>Initiate the BCG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_CTC__c.field-meta.xml
<CustomField>
    <fullName>Current_CTC__c</fullName>
    <label>Current CTC</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Expected_CTC__c.field-meta.xml
<CustomField>
    <fullName>Expected_CTC__c</fullName>
    <label>Expected CTC</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bangalore</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Noida</fullName>
            </value>
            <value>
                <fullName>Patna</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Notice_Period__c.field-meta.xml
<CustomField>
    <fullName>Notice_Period__c</fullName>
    <label>Notice Period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Immediate</fullName>
            </value>
            <value>
                <fullName>1 Week</fullName>
            </value>
            <value>
                <fullName>15 Days</fullName>
            </value>
            <value>
                <fullName>1 Month</fullName>
            </value>
            <value>
                <fullName>2 Months</fullName>
            </value>
            <value>
                <fullName>3 Months</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Position_Name__c.field-meta.xml
<CustomField>
    <fullName>Position_Name__c</fullName>
    <label>Position</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Position__c.Position_Status__c</field>
            <operation>notEqual</operation>
            <value>Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Technical_Skills__c.field-meta.xml
<CustomField>
    <fullName>Technical_Skills__c</fullName>
    <label>Technical Skills</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Adv. Java</fullName>
            </value>
            <value>
                <fullName>ASAP Net</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>C# Net</fullName>
            </value>
            <value>
                <fullName>C++</fullName>
            </value>
            <value>
                <fullName>Core Java</fullName>
            </value>
            <value>
                <fullName>J2EE</fullName>
            </value>
            <value>
                <fullName>Manual Testing</fullName>
            </value>
            <value>
                <fullName>Ms. Net</fullName>
            </value>
            <value>
                <fullName>ORACEL</fullName>
            </value>
            <value>
                <fullName>QTP</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>Selinium</fullName>
            </value>
            <value>
                <fullName>SQL Server</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MessagingUtility.cls
public class MessagingUtility 
{
	public static void SendEmailToCandidate(Candidate__c cnd, string emailsubject)
    {
        if(cnd != null)
        {
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            
            string[] toaddress = new string[]{cnd.Email_Id__c, '59mukulkr@gmail.com'};
                
            email.setToAddresses(toaddress);
            
            string[] ccaddress = new string[]{cnd.Email_Id__c, 'praveenkr810@gmail.com'};
                //email.setCcAddresses(ccaddress);
            string[] bccaddress = new string[]{cnd.Email_Id__c, 'support@gmail.com'};
              //  email.setBccAddresses(bccaddress);
            
            email.setReplyTo('praveenkr810@gmail.com');
            email.setSenderDisplayName('Accenture recruitment team');
            
            email.setSubject(emailsubject);
            
            string emailbody ='Dear ' + cnd.Name + ', Thanks for showing the interest in our organization open position.'+
                				'Your cnadidature has been submitted successfully for the position. '+ cnd.Position_Name__c +
                				'Once or our HR will get back to you, once your profile get shortlisted';
           // email.setPlainTextBody(emailbody);    
            string htmlemailbody = 'Dear ' + cnd.Name + ', <br/><br/>'+
                					'Thanks for showing interest in our organization position. <br/><br/>'+
                					'We are please to inform you, that your candidature has been submitted sucessfully. <br/>'+
                					'Please have a look into you details ....<br/><br/>'+
                					'Candidate ID: '+ cnd.Candidate_ID_c__c+
                					'<br/>Candidate Name: '+ cnd.Name+
            						'<br/>Location: '+ cnd.Location__c+
            						'<br/>Email ID : '+ cnd.Email_Id__c+
            						'<br/>Candidature Status : ' + cnd.Candidature_Status__c+
            						'<br/>Current Ctc: '+ cnd.Current_CTC__c+
                					'<br/>Expected ctc: '+ cnd.Expected_CTC__c+
                					'<br/>Notice Period: '+ cnd.Notice_Period__c+
                					'<br/>Technical Skills: '+ cnd.Technical_Skills__c+
                					'<br/><br/> Thanks & Regards, <br/>'+
                					'Talent Aquisition Team, <br/> Accenture Inc';
            
            email.setHtmlBody(htmlemailbody);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
            						                                        
            
		}
    }
    public static void SendEmailToCandidate(List<Candidate__c> lstcnd, string emailsubject)
    {
        if(!lstcnd.isEmpty())
        {
            list<Messaging.SingleEmailMessage> emailNotification = new  list<Messaging.SingleEmailMessage>();
             
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            for(Candidate__c cnd :  lstcnd)
            {
                       
            string[] toaddress = new string[]{cnd.Email_Id__c, '59mukulkr@gmail.com'};
                
            email.setToAddresses(toaddress);
            
            string[] ccaddress = new string[]{cnd.Email_Id__c, 'praveenkr810@gmail.com'};
                //email.setCcAddresses(ccaddress);
            string[] bccaddress = new string[]{cnd.Email_Id__c, 'support@gmail.com'};
              //  email.setBccAddresses(bccaddress);
            
            email.setReplyTo('praveenkr810@gmail.com');
            email.setSenderDisplayName('Accenture recruitment team');
            
            email.setSubject(emailsubject);
            
            string emailbody ='Dear ' + cnd.Name + ', Thanks for showing the interest in our organization open position.'+
                				'Your cnadidature has been submitted successfully for the position. '+ cnd.Position_Name__c +
                				'Once or our HR will get back to you, once your profile get shortlisted';
           // email.setPlainTextBody(emailbody);
            
            string htmlemailbody = 'Dear ' + cnd.Name + ', <br/><br/>'+
                					'Thanks for showing interest in our organization position. <br/><br/>'+
                					'We are please to inform you, that your candidature has been submitted sucessfully. <br/>'+
                					'Please have a look into you details ....<br/><br/>'+
                					'Candidate ID: '+ cnd.Candidate_ID_c__c+
                					'<br/>Candidate Name: '+ cnd.Name+
            						'<br/>Location: '+ cnd.Location__c+
            						'<br/>Email ID : '+ cnd.Email_Id__c+
            						'<br/>Candidature Status : ' + cnd.Candidature_Status__c+
            						'<br/>Current Ctc: '+ cnd.Current_CTC__c+
                					'<br/>Expected ctc: '+ cnd.Expected_CTC__c+
                					'<br/>Notice Period: '+ cnd.Notice_Period__c+
                					'<br/>Technical Skills: '+ cnd.Technical_Skills__c+
                					'<br/><br/> Please click on this link to view the record. <a.href= '+ system.Url.getSalesforceBaseUrl().ToExternalform()+ '/'+ cnd.Id+ '> click Here to view the records</a> <br/><br/>'+
                					'<br/><br/> Thanks & Regards, <br/>'+
                					'Talent Aquisition Team, <br/> Accenture Inc';
            
            email.setHtmlBody(htmlemailbody);
                emailNotification.add(email);
                
            } 			
            if(! emailNotification.isEmpty())
            {
                Messaging.SendEmailResult[] res =  Messaging.sendEmail(emailNotification, false);
            }
            
		}
}
    
    public static void SendNotificationToContactForPanDetails()
    {
        // Get the contact records, to send the notification
        
        Map<id, Contact> mapcontoSend =new Map<id, Contact>([select id, firstname, email, pan_number__c from Contact
                                                         where pan_number__c = null and email != null]);
    if(!mapcontoSend.isempty())
    {
        // Create the object of massemailmessage class..
        
        Messaging.MassEmailMessage massEmail = new Messaging.MassEmailMessage();
        list<ID> contacid = new list<id>();
        
        contacid.addall(mapcontoSend.keyset());
        // supply the list of contact id's..
        massemail.setTargetObjectIds(contacid);
        
        emailtemplate temp = [select id, name from emailtemplate where name = 'PAN Number Notification Template' limit 1];
        
        if(temp != null)
        {
            massemail.setTemplateId(temp.Id);
            
            messaging.sendEmail(new messaging.MassEmailMessage[]{massemail});
        }
   
	}
    }
    
    public static void SendBatchProcessNotification(AsyncApexJob jobDetails)
    {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        
        string[] toadress = new string[]{ jobdetails.createdby.email, '59mukulkr@gmail.com'};
            email.setToAddresses(toadress);
        string emailsubj = 'Batch job: UpdateContactBatch - '+ jobdetails.id + 'Status Notification';
        	email.setSubject(emailsubj);
        
        string emailcontent = 'Please find the below process status for the batch job: updatecontactsBatch. <br/>'+
            				'<br/> Batch Job id is ...'+ jobdetails.id+
            				'<br/> job status .... '+ jobdetails.status+
            				'<br/> Total Batch Processed .... '+ jobdetails.jobItemsProcessed+
            				'<br/> Total Number of Batches ..... '+ jobdetails.totalJobItems+
            				'<br/> Number of batvhes failed ..... '+ jobdetails.NumberofErrors;
        
        email.setHtmlBody(emailcontent);
        email.setReplyTo('support@dell.com');
        email.setSenderDisplayName('Contact Batch Processing status notification');
        
        Messaging.sendEmail(new Messaging.singleEmailMessage[]{email});
		}
}