force-app/main/default/objects/Page_View__c/Page_View__c.object-meta.xml
<CustomObject>
    <label>Page View</label>
    <nameField>
        <label>Page View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Page Views</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Page_View__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Page_Views</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MyPageview_1ApexController.cls
public class MyPageview_1ApexController {
    
    @RemoteAction
    public static string getChartData(String user, Date startDate, Date endDate) {
      system.debug('user'+user+'Start Date '+startDate +'End Date'+endDate);
        // Query to retrieve data based on user, startDate, and endDate
        List<AggregateResult> results = [SELECT User__c, SUM(Duration__c) totalDuration FROM Page_View__c WHERE User__c = :user AND CreatedDate >= :startDate AND CreatedDate <= :endDate GROUP BY User__c ];

     return 'Praveen';
}
}